In [3]:
7**4

2401

In [8]:
s = "Hi there Sam!"

In [10]:
myList = s.split(' ');

In [15]:
myList

['Hi', 'there', 'Sam!']

In [13]:
planet = "Earth"

In [16]:
diameter = 12742

In [18]:
s = "The diameter of the {} is {} kilometers".format(planet, diameter)

In [21]:
s

'The diameter of the Earth is 12742 kilometers'

In [27]:
s = "The diameter of the {y} is {x} kilometers".format(x = planet, y = diameter)

In [30]:
s

'The diameter of the 12742 is Earth kilometers'

In [33]:
for i in range(5):
    print(i)

0
1
2
3
4


In [35]:
for i in range(1, 7):
    print(i)

1
2
3
4
5
6


In [37]:
for i in range(0,10,2):
    print(i)

0
2
4
6
8


In [39]:
myList

['Hi', 'there', 'Sam!']

In [41]:
myList.clear()

In [43]:
myList

[]

In [46]:
for i in range(20, 2):
    print(i)

In [65]:
for i in range(0, 20, 2):
    myList.append(i)

In [52]:
myList

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [56]:
for item in myList:
    item = item*2
    print(item)

0
4
8
12
16
20
24
28
32
36
0
4
8
12
16
20
24
28
32
36


In [67]:
myList

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18]

In [69]:
myList.clear()

In [72]:
myList

[]

In [74]:
def func():
    print("Hello")

In [77]:
func()

Hello


In [83]:
def func(item):
    print(item)

In [85]:
func(2)

2


In [87]:
import numpy as np

In [89]:
np.__version__

'1.24.3'

In [91]:
np.random.rand(4)

array([0.23959255, 0.19688703, 0.89566288, 0.63328524])

In [123]:
np.random.rand(4, 2)

array([[0.32646206, 0.65347412],
       [0.83880046, 0.77263918],
       [0.1239888 , 0.94442162],
       [0.05852816, 0.58686675]])

In [126]:
np.random.randn(5, 6)

array([[ 0.23970549,  0.05958338,  0.71596642, -0.2860133 ,  0.46672144,
        -0.86215121],
       [ 0.68964477,  0.81129653, -2.10185563, -0.25180983,  0.07544508,
        -0.72274665],
       [-0.22265501,  0.40714029, -0.11750184,  0.12402119, -0.04152415,
        -0.19348072],
       [ 0.31063258, -1.83130157,  0.50851192,  0.12795168, -1.17720695,
         0.5691298 ],
       [ 0.74264848,  0.97656628,  1.49307852,  0.5340563 , -0.19432364,
        -1.53598546]])

In [208]:
np.random.randint(5, 45, 5)

array([44, 16, 15,  5, 32])

In [212]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [214]:
np.arange(0, 25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [216]:
arr = np.arange(0, 25)

In [222]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [237]:
ranarr = np.random.randint(0, 101, 10)

In [243]:
ranarr

array([73, 52, 18, 71, 15, 44,  0, 12, 17, 75])

In [244]:
ranarr.max()

75

In [245]:
ranarr.argmax()

9

In [247]:
ranarr.min()

0

In [249]:
ranarr.argmin()

6

In [252]:
ranarr.dtype

dtype('int32')

In [255]:
ranarr.shapehttp://localhost:8888/notebooks/ML/Untitled.ipynb

(10,)

In [260]:
ranarr = ranarr.reshape(5, 2)

In [262]:
ranarr.shape

(5, 2)

In [274]:
ranarr = ranarr.reshape(1, 10)

In [276]:
ranarr.shape

(1, 10)

In [278]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [282]:
np.arange(0, 101, 6)

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [287]:
np.zeros((5, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [289]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [296]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [299]:
arr = np.arange(0, 11)

In [301]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [306]:
new_arr = arr[1:5]

In [308]:
new_arr

array([1, 2, 3, 4])

In [309]:
new_arr[:] = 99

In [311]:
new_arr

array([99, 99, 99, 99])

In [313]:
arr

array([ 0, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [315]:
arr = np.arange(0, 11)

In [320]:
copy_of_arr = arr[1:5].copy()

In [322]:
copy_of_arr

array([1, 2, 3, 4])

In [324]:
copy_of_arr[1 : 3] = 99 

In [326]:
copy_of_arr

array([ 1, 99, 99,  4])

In [327]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])